# Create your Kivy layout in the kv language here
BoxLayout:
    orientation: 'horizontal'
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'Sort by:'
    Spinner:
    Label:
        text: 'Add new place...'
    Label:
        text: 'Name : '
    Label:
        text: 'Country : '
    Label:
        text: 'Priority : '
    Button:
        text: 'Add Place'
    Button:
        text: 'Clear'
